name: Generate JOP Java Silicon GDSII
on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  openlane_harden:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install OpenLane Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openlane

      - name: Run OpenLane Synthesis and Routing
        run: |
          # Uses the runner's built-in Docker engine to execute the compiler
          python3 -m openlane --design-dir . --pdk sky130 config.json
